### PR TITLE
Move branch name into env variable

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Review by olexandr-konovalov — APPROVED** [review]

**Comment by fingolfin** [comment]
With <https://github.com/gap-system/gap-docker-stable-4.11/pull/1>, <https://github.com/gap-system/gap-docker-stable-4.10/pull/3> and <https://github.com/gap-system/gap-docker-master/pull/3>, there is only a single line differing in the Dockerfiles. We might even be able to merge the three repositories into one, if we use the fact that Dockerfile builds can be parametrized; but we first need to verify that this works with Docker Hub (and how).

**Comment by zickgraf** [comment]
I see one problem with merging the repositories which one might want to keep in mind: I assume that at some point in the future, GAP 4.10 or the packages distributed with GAP 4.10 will become incompatible with an updated version of `gap-docker-base` (for example because dependencies like Singular are updated). Then one either has to drop support for the GAP 4.10 image or one has to ensure that the GAP 4.10 image is not updated anymore. This might be a problem if the repositories are merged because then probably any commit triggers a rebuild for all ~branches~ parameters.

**Comment by olexandr-konovalov** [comment]
Yes, I agree with @zickgraf that we should be careful. Let's not rush with that.

**Comment by fingolfin** [comment]
@zickgraf wrote:
> This might be a problem if the repositories are merged because then probably any commit triggers a rebuild for all branches.

A commit to a branch of course only triggers a rebuild of that branch, not of all branches. So this really isn't a problem.

As to the fear that gap-docker-base becomes incomapatible: But the exact same issue already exists now.

And of course nothing is being rushed here. As usual, I am Mr. "Do it incrementally"

**Comment by zickgraf** [comment]
> A commit to a branch of course only triggers a rebuild of that branch, not of all branches. So this really isn't a problem.

Sorry, I used the word "branch" in the wrong way. I assume that there would only be a single branch, which is build with different parameters. My statement should read: "This might be a problem if the repositories are merged because then probably any commit triggers a rebuild for all parameters."

> As to the fear that gap-docker-base becomes incomapatible: But the exact same issue already exists now.

Yes, but if no one commits to `gap-docker-stable-4.10`, no rebuild is ever triggered, so the image on Docker Hub (still based on an old version of `gap-docker-base`) stays functional.

**Pull request merged**
